name: "SonarCloud Analysis"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for full history analysis

      # 2. Set up JDK 11 (required for SonarCloud)
      - name: "Set up JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3. Cache SonarCloud packages
      - name: "Cache SonarCloud packages"
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # 4. Run SonarCloud scan
      - name: "SonarCloud Scan"
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectKey: Niki-ta0_Docker   # Your project key
          organization: Niki-ta0        # Your organization name
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
